### PR TITLE
updated to cms 3.0.12, removed zinnia

### PR DESCRIPTION
**Pull request by lkleuver**
this is a tricky one.
I upgraded to cms 3.0.12 which features
manage.py cms uninstall apphooks ZinniaApphook
and
manage.py cms delete_orphaned_plugins

But to get it to work I manually removed the zinnia tables from the DB, not sure how to do this on Heroku.

### CODE REVIEW

**Comment by cschaffner** [comment]
I think the best way is to put the required sql statements into a script. Have you already done this? There is a file called sqlscripts/clearzinnia.sql ...

**Comment by cschaffner** [comment]
Hmm, when running
./manage.py cms delete_orphaned_plugins

I get
......
django.db.utils.IntegrityError: update or delete on table "cms_cmsplugin" violates foreign key constraint "cmsplugin_ptr_id_refs_id_03752e6e" on table "cmsplugin_filerimage"
DETAIL:  Key (id)=(5) is still referenced from table "cmsplugin_filerimage".

Do you also have that?

**Comment by lkleuver** [comment]
yes and ignored it

**Comment by cschaffner** [comment]
So, the right order of actions is:
heroku run ./manage.py cms uninstall apphooks ZinniaApphook
cat sqlscripts/clearzinnia.sql | heroku pg:psql --app crunchsite
heroku run ./manage.py cms delete_orphaned_plugins
(results in error about the cmsplugin_filer, but at least the zinnia stuff is removed)

**Pull request merged**
